package io.github.maybee.lexeme.common.exception;


/**
 * An exception to be thrown if two attributes can't be merged (i.e. the merged value is not longer a valid
 * value for this attribute)
 * @author sholzer (11.02.2015)
 */
public class AttributesCantBeMergedException extends XMLMergeException {

    /**
     * generated by Eclipse
     */
    private static final long serialVersionUID = -7349146805487078768L;

}
