package io.github.maybee.lexeme.common.exception;


/**
 * An exception to be thrown if two contents can't be merged (i.e. the merged value is not longer a valid
 * value for this content)
 * @author sholzer (11.02.2015)
 */
public class ContentsCantBeMergedException extends XMLMergeException {

    /**
     * generated by Eclipse
     */
    private static final long serialVersionUID = 4545265088263321851L;

}
