package io.github.maybee.lexeme.common.exception;


/**
 * An exception thrown if it's tried to merge two elements who can't be merged (i.e. different element tags)
 * @author sholzer (11.02.2015)
 */
public class ElementsCantBeMergedException extends XMLMergeException {

    /**
     * @param string
     *            the message describing the cause of the Exception
     * @author sholzer (21.04.2015)
     */
    public ElementsCantBeMergedException(String string) {
        // TODO Auto-generated constructor stub
    }

    /**
     *
     * @author sholzer (21.04.2015)
     */
    public ElementsCantBeMergedException() {
    }

    /**
     * generated by Eclipse
     */
    private static final long serialVersionUID = -8705161220178514264L;

}
