package com.github.maybeec.lexeme.common.exception;

/**
 * An exception to be thrown if two contents can't be merged (i.e. the merged value is not longer a valid value for this
 * content)
 */
public class ContentsCantBeMergedException extends XMLMergeException {

  /**
   * generated by Eclipse
   */
  private static final long serialVersionUID = 4545265088263321851L;

}
