package com.github.maybeec.lexeme.common.exception;

/**
 * An exception thrown if it's tried to merge two elements who can't be merged (i.e. different element tags)
 */
public class ElementsCantBeMergedException extends XMLMergeException {

  /**
   * Create a new ElementsCantBeMergedException.
   */
  public ElementsCantBeMergedException() {

    super();
  }

  /**
   * Create a new ElementsCantBeMergedException wrapping an existing exception.
   *
   * <p>
   * The existing exception will be embedded in the new one, and its message will become the default message for the
   * ElementsCantBeMergedException.
   * </p>
   *
   * @param e The exception to be wrapped in a ElementsCantBeMergedException.
   */
  public ElementsCantBeMergedException(Exception e) {

    super(e);
  }

  /**
   * Create a new ElementsCantBeMergedException.
   *
   * @param message The error or warning message.
   */
  public ElementsCantBeMergedException(String message) {

    super(message);
  }

  /**
   * Create a new ElementsCantBeMergedException from an existing exception.
   *
   * <p>
   * The existing exception will be embedded in the new one, but the new exception will have its own message.
   * </p>
   *
   * @param message The detail message.
   * @param e The exception to be wrapped in a ElementsCantBeMergedException.
   */
  public ElementsCantBeMergedException(String message, Exception e) {

    super(message, e);
  }

  /**
   * generated by Eclipse
   */
  private static final long serialVersionUID = -8705161220178514264L;

}
