package com.github.maybeec.lexeme.common.exception;

/**
 *
 * @author sholzer (18.02.2015)
 */
public class MultipleInstancesOfUniqueElementException extends ElementsCantBeMergedException {

    /**
     * @param string
     *            Exception message
     * @author sholzer (Sep 11, 2015)
     */
    public MultipleInstancesOfUniqueElementException(String string) {
        super(string);
    }

    /**
     * Generated by eclipse
     */
    private static final long serialVersionUID = -1346925895199808914L;

}
