package com.github.maybeec.lexeme.common.exception;

/**
 * A generic exception thrown during the merge process if this library
 * @author sholzer (11.02.2015)
 */
public class XMLMergeException extends Exception {

    /**
     * @param message
     *            String
     * @author sholzer (10.03.2015)
     */
    public XMLMergeException(String message) {
        super(message);
    }

    /**
     *
     * @author sholzer (10.03.2015)
     */
    public XMLMergeException() {

    }

    /**
     * generated by Eclipse
     */
    private static final long serialVersionUID = 2939508045103474155L;

}
